Corrections
zloirock/core-js pull request #1033
Opened 2022-01-03 09:39 UTC by ritikbanger

Enhanced the Doc by removing grammatical errors.

2022-01-03 17:23 UTC, zloirock requested changes
Thanks, but some fixes are required.

2022-01-03 17:23 UTC, zloirock commented on docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md
> +Or you can contribute in another way: you can help improve code, tests or, documentation (currently, `core-js` documentation is terrible!).
This comma is not required.

2022-01-03 17:23 UTC, zloirock commented on docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md
> +Many years ago, I started writing a library that I needed as the core of my JavaScript applications: this library contained polyfills and some utilities for common needs. After some time, it was publ
It makes no sense.

2022-01-03 17:23 UTC, zloirock commented on docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md
> +### Packages, entry points, and modules names
This comma is not required.

2022-01-03 17:23 UTC, zloirock commented on docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md
> +In previous versions of `core-js`, modules with polyfills for stable ECMAScript features and ECMAScript proposals were prefixed with `es6.` and `es7.` respectively. It was a decision taken in 2014 wh
The same, makes no sense.

2022-01-03 17:23 UTC, zloirock commented on docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md
> +- [`core-js-pure`](https://www.npmjs.com/package/core-js-pure), which provides polyfills without polluting the global environment. It's the equivalent of `core-js/library` from `core-js@2`. (~440KB)
I would prefer "pollution" more.

2022-01-03 17:23 UTC, zloirock commented on docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md
> +For almost all users, for optimization of `core-js` import, I recommend using [`babel`](#Babel). However, for some cases still a useful [`core-js-builder`](http://npmjs.com/package/core-js-builder).
`a` makes no sense, it's better to completely rewrite this sentence. I don't see a sense in changing `which` -> `that` in this case too.

2022-01-03 17:23 UTC, zloirock commented on docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md
> +[`@babel/polyfill`](https://babeljs.io/docs/en/next/babel-polyfill.html) is a wrapper package that only includes imports of stable `core-js` features (in Babel 6 it also included proposals) and `rege
The same.

2022-01-03 17:23 UTC, zloirock commented on docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md
> +`@babel/preset-env` now injections polyfills required for syntax features: iterators when using `for-of`, destructuring, spread and `yield` delegation; promises when using dynamic `import`, async fun
This comma is also not required.

2022-01-03 17:23 UTC, zloirock commented on docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md
> +Another notable change is the support of ECMAScript proposals. By default, `@babel/plugin-transform-runtime` does not inject polyfills for proposals and use entry points that do not include them but,
The same.

2022-01-03 17:23 UTC, zloirock commented on docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md
> +The biggest missing important feature is property descriptors: when they aren't available, some features can't be polyfilled because they either are accessors (like `RegExp.prototype.flags` or `URL`
`workaround` should not be split.

2022-01-03 17:23 UTC, zloirock commented on docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md
> +The main reason why `core-js` doesn’t include them was that it would have seriously increased bundles size and it would have forced `core-js` users to load features that might not have been needed. N
The same.

2022-01-03 17:23 UTC, zloirock commented on docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md
> +We will be able to get a built-in module just by using ES modules syntax with a special prefix. This syntax haven't equal based on the previous version of the language - transpiled modules will not b
`any` shouldn't be removed.

2022-01-04 12:51 UTC, zloirock approved these changes

2022-01-04 13:53 UTC, merged

2022-01-05 11:45 UTC, ritikbanger commented
Thanks for merging!